name: Static code analysis (branch)

on:
  push:
    branches: [ feature_branch* ]
  pull_request:
    branches: [ feature_branch* ]

permissions:
  contents: read
  pages: write
  id-token: write


jobs:
  run-cpptest-make:
    name: Analyze project with C/C++test

    # Specifies required permissions for upload-sarif action
    permissions:
      # required for all workflows
      security-events: write
      # only required for workflows in private repositories
      actions: read
      contents: read

    # Specifies the type of runner that the job will run on.
    runs-on: self-hosted

    # Steps represent a sequence of tasks that will be executed as part of the job.
    steps:

    # Checks out your repository under $GITHUB_WORKSPACE, so that your job can access it.
    - name: Checkout code
      uses: actions/checkout@v4


    - name: Get changed files
      id: changed-files
      uses: tj-actions/changed-files@v46
      # To compare changes between the current commit and the last pushed remote commit set `since_last_remote_commit: true`. e.g
      with:
        files: |
          **.inl
          **.cpp
        files_ignore: |
          **/test_*.cpp

    - name: Prepare excludes
      if: steps.changed-files.outputs.any_changed == 'true'
      env:
        ALL_CHANGED_FILES: ${{ steps.changed-files.outputs.all_changed_files }}
        CPPTEST_CC_PSRC: iceoryx_hoofs/cmake/modified.lst
      run: |
        list=( $ALL_CHANGED_FILES )
        for file in ${list[@]}; do
          echo "$file" >> $CPPTEST_CC_PSRC
        done
        ls -la $CPPTEST_CC_PSRC
        cat $CPPTEST_CC_PSRC


    # Configures your CMake project. Be sure the compile_commands.json file is created.
    - name: Configure project
      run: cmake -Bbuild -Hiceoryx_meta -DBUILD_TEST=ON -DINTROSPECTION=OFF -DBINDING_C=OFF -DCPPTEST_COVERAGE=ON -DCMAKE_EXPORT_COMPILE_COMMANDS=ON -DCMAKE_VERBOSE_MAKEFILE=ON -DCMAKE_PREFIX_PATH=$(pwd)/build/dependencies/

    # Builds your CMake project. (This step is optional, as it is not required for code analysis).
    #- name: Build project (optional)
    #  run: cmake --build build

    # Runs code analysis with C/C++test.
    - name: Run C/C++test
      # Use the 'run-cpptest-action' GitHub action.
      uses: parasoft/run-cpptest-action@2.0.2
      # Optional parameters for 'run-cpptest-action'.
      with:
        # For CMake-based projects, use a compile_commands.json file as the input for analysis. 
        input: build/compile_commands.json
        testConfig: 'builtin://MISRA C++ 2023'
        compilerConfig: 'gcc_10-64'
        # Uncomment if you are using C/C++test 2020.2 to generate a SARIF report:
        # reportFormat: xml,html,custom
        # additionalParams: '-property report.custom.extension=sarif -property report.custom.xsl.file=${PARASOFT_SARIF_XSL}'
        additionalParams: -showdetails -exclude "**/googletest/**" -exclude "**/test/**" -exclude "**/testing/**" -exclude "**/googlemock/**" -exclude "**/iceoryx_examples/**" -property scontrol.rep1.git.workspace=${{github.workspace}} -include $CPPTEST_CC_PSRC
# -resource ${{github.workspace}}/iceoryx_hoofs

    # Uploads analysis results in the SARIF format, so that they are displayed as GitHub code scanning alerts.
    - name: Upload results (SARIF)
      if: always()
      uses: github/codeql-action/upload-sarif@v3
      with:
        sarif_file: reports/report.sarif
    
    # Uploads an archive that includes all report files (.xml, .html, .sarif).
    - name: Archive reports
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: CpptestReports
        path: reports/*.*

 